// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactTestCaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactTestCase() {
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
    WebDriver driver=new ChromeDriver();
    driver.get("https://yashesh07.github.io/SE_project-Intitute_website/index.html");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("CONTACT")).click();
    driver.switchTo().frame(0);
    {
      WebElement element = driver.findElement(By.cssSelector(".gm-style > div:nth-child(2) > div:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".gm-style > div:nth-child(2) > div:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".gm-style > div:nth-child(2) > div:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".gm-style > div:nth-child(2) > div:nth-child(2)")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("Name")).click();
    driver.findElement(By.id("Name")).sendKeys("Yashesh Bhavsar");
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("202011017@diu.iiitvadodara.ac.in");
    driver.findElement(By.id("Subject")).click();
    driver.findElement(By.id("Subject")).sendKeys("Regarding scholarship");
    driver.findElement(By.id("Message")).click();
    driver.findElement(By.id("Message")).click();
    driver.findElement(By.id("Message")).click();
    driver.findElement(By.id("Message")).sendKeys("I need list of scholarships avilable");
    driver.findElement(By.cssSelector(".hero-btn")).click();
  }
}
