// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase1() {
    driver.get("http://127.0.0.1:5500/wtt-website-main/index.html");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("CONTACT")).click();
    driver.findElement(By.id("Name")).click();
    driver.findElement(By.id("Name")).sendKeys("Yashesh Bhavsar");
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("202011017@diu.iiitvadodara.ac.in");
    driver.findElement(By.id("Subject")).click();
    driver.findElement(By.id("Subject")).sendKeys("Coding Culture");
    driver.findElement(By.id("Message")).click();
    driver.findElement(By.id("Message")).sendKeys("Coding culture is very good.");
    driver.findElement(By.cssSelector(".hero-btn")).click();
  }
}
